Added service's interface files
pagopa-archive/interop-be-probing-api pull request #1
Opened 2023-02-08 16:23 UTC by gdellorusso

2023-02-09 10:13 UTC, galales requested changes

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +          application/json-patch+json:
```suggestion
          application/json:
```

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +          application/json-patch+json:
```suggestion
          application/json:
```

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +            The update has been successfully completed
if the endpoint does not return a body, a `204` code is more suitable

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +        '200':
same for `204` code

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +   "/eservices/{eserviceId}/versions/{versionId}/updateStatus":
I suggest consistencies in quotes.
We could use the single quote, unless specific use cases require double quotes

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +        '200':
same for `204`

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +          $ref: '#/components/schemas/Action'
out of curiosity: why the EService status is changed with the new status (ACTIVE/INACTIVE) while the probing with the action (ENABLE/DISABLE)?

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +          minimum : 1
is there a reason why we need these two fields when changing the probing status?

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +          title: Service verification frequency
```suggestion
          title: Service verification frequency in minutes
```

2023-02-09 10:13 UTC, galales commented on docs/openapi/probing-service.yaml
> +        '200':
`204` is enough, we do not need a body
```suggestion
        '204':
```

2023-02-09 10:13 UTC, galales commented on docs/openapi/probing-service.yaml
> +        - Read
if this can be useful to us, I would call it something like
```suggestion
      tags:
        - InteropProbing
```

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +  title: 'E-Service Monitor PDND API specifications'
when referencing to interoperability platform, let's use `Interop` instead of `PDND`
```suggestion
  title: 'E-Service Monitor Interop API specifications'
```
same for all other references

2023-02-09 10:13 UTC, galales commented on docs/openapi/probing-service.yaml
> +      Read data operations.
these are not required here
```suggestion
```

2023-02-09 10:13 UTC, galales commented on docs/openapi/probing-service.yaml
> +   "/probing":
```suggestion
   "/interop/probing":
```

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +      Insert/update data operations.
`Read` and `Write` operations are already defined by the HTTP verb.
We could split by
```suggestion
  - name: EServices
    description: >-
      Operations on EServices registry
  - name: Probing
    description: >-
      Operations on probing settings
```
This is just a suggestion, if you have strong opinions let's discuss it

2023-02-09 10:13 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +   "/eservices/{eserviceId}/versions/{versionId}/updateStatus":
I suggest to use `state` for the "current condition of an object" (EService active/inactive), while `status` for the outcome of an operation (response 400/500)
```suggestion
   "/eservices/{eserviceId}/versions/{versionId}/updateState":
```
Same applies for other occurrences in the specs

2023-02-09 11:05 UTC, gdellorusso commented on docs/openapi/api-external-interop-v1.yaml
> +          $ref: '#/components/schemas/Action'
we planned to use "ACTIVE" and "INACTIVE" in anticipation of possible new state values insertion reflecting PDND ones.
In addition we used two different data structures (Probing state and Services state) to decouple the input data for these two services.
Do we need to merge them using only one data structure having ENABLE/DISABLE values?

2023-02-09 11:08 UTC, gdellorusso commented on docs/openapi/api-external-interop-v1.yaml
> +          minimum : 1
this is a typo, we removed it.

2023-02-09 11:20 UTC, gdellorusso commented on docs/openapi/probing-service.yaml
> +      Read data operations.
We checked the yaml content toward the Italian API Guidelines Checker (https://italia.github.io/api-oas-checker/) and without these lines the tool reports 5 errors. 
Do we have to remove these lines or we leave them?

2023-02-09 17:52 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +          $ref: '#/components/schemas/Action'
No objections in keeping them separated, I would just suggest to use the same approach and use a state also for probing (whose values may be ENABLED/DISABLED, if you prefer using different values).

Also, it might be worth to rename the models to `EServiceState` and `ProbingState` to be more self explanatory

2023-02-09 18:03 UTC, galales requested changes

2023-02-09 18:03 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +    OpenAPI specification for E-Service Monitor's services exposed for the PDND platform
```suggestion
    OpenAPI specification for E-Service Monitor's services exposed for the Interop platform
```
`PDND` needs to be replaced everywhere with `Interop`

2023-02-09 18:03 UTC, galales commented on docs/openapi/probing-service.yaml
> +   "/interop/probing":
quotes consistency
```suggestion
   '/interop/probing':
```

2023-02-10 12:08 UTC, galales commented on docs/wsdl/probing.wsdl
> +						<xsd:element name="status">
`status` field should be defined mandatory

2023-02-10 12:08 UTC, galales commented on docs/wsdl/probing.wsdl
> +						<xsd:element name="descrizione">
```suggestion
						<xsd:element name="description">
```

2023-02-10 12:08 UTC, galales commented on docs/openapi/probing-service.yaml
> +      Read data operations.
OpenApi specs allow to defined a partial schema, but let's keep it like this for now and change it in case it generates confusion

2023-02-10 13:49 UTC, gdellorusso commented on docs/wsdl/probing.wsdl
> +						<xsd:element name="status">
done

2023-02-10 14:37 UTC, galales commented on docs/wsdl/probing.wsdl
> +						<xsd:element minOccurs="0" name="status">
I may be wrong, but shouldn't this be
```suggestion
						<xsd:element minOccurs="1" name="status">
```

2023-02-10 14:44 UTC, gdellorusso commented on docs/wsdl/probing.wsdl
> +						<xsd:element minOccurs="0" name="status">
I always found/used minOccurs="0" to indicate a "required" field.
I tried to generate the related java classes and it correctly inserts the annotation @XmlElement(required = true)

2023-02-10 14:51 UTC, galales commented on docs/wsdl/probing.wsdl
> +						<xsd:element minOccurs="0" name="status">
great, thanks for the confirmation 👍

2023-02-10 14:52 UTC, galales approved these changes

2023-02-10 14:54 UTC, merged