Feature/iesp 26
pagopa-archive/interop-be-probing-api pull request #2
Opened 2023-02-14 12:14 UTC by acolella92

2023-02-14 14:38 UTC, nttdata-rtorsoli requested changes
Maybe it is better to talk about this project in a dedicated meeting

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Setter
Use `@`Data with `@`NoArgsConstructor, use also `@`Builder

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String versionid;
`@`Version if it is a version field, managed automatically for optimistic lock

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String eserviceid;
ManyToOne?

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @GeneratedValue
Put Strategy field

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Table(name="eservices")
Miss schema

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String eserviceType;
Is it an Enum?

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String state;
Is it an enum?

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Entity
Use an @EntityListeners for logging and update timestamp fields

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Entity
Missing jsr-380 validation for fields

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/rest/EserviceController.java
> +    public ResponseEntity<Void> updateEserviceFrequency(UUID eserviceId, UUID versionId, ChangeProbingFrequencyDTO changeProbingFrequencyDTO) throws Exception {
Request body for endpoint has to be named with suffix Request

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/rest/EserviceController.java
> +        eserviceService.updateEserviceState(eserviceId, versionId, changeEServiceStateDTO.geteServiceState());
Use mapstruct to convert Request into a DTO

2023-02-14 14:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +        eserviceRepository.updateEserviceStateByEserviceIdAndVersionId(
Use mapstruct to convert DTO to Entity

2023-02-14 16:33 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Setter
The @Getter and @Setter annotations have been used instead of the ones listed above because they will generate methods that mostly won't be used and this will lower the junit coverage percentage, is it mandatory to use these annotations?

2023-02-14 16:34 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String versionid;
The versionId field is a unique identifier provided by PDND

2023-02-14 16:35 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String eserviceid;
The eserviceId is a unique identifier for the eservice and will be provided by PDND, it's not an external reference to another entity

2023-02-14 16:36 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Setter
It's important to have equals, hashcode and toString and a noArgsConstructor in every model

2023-02-14 16:37 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Table(name="eservices")
The database schema will be specified in the application.properties file, is it mandatory to add it here too?

2023-02-14 16:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String versionid;
In this we need to manage @Version for Entity and versionId at the same time, we need to study further on this

2023-02-14 16:40 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String versionid;
the field isn't the entity version, it's just an identifier generated by PDND.

2023-02-14 16:42 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String eserviceid;
OK, maybe this application do not need to have visibility on EServices

2023-02-14 16:45 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Table(name="eservices")
Yes, if you auto generated Entities spring set this property for you, if you generate Entity by your own then you need to apply this property by hand.

2023-02-14 16:49 UTC, nttdata-rtorsoli requested changes

2023-02-14 16:49 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/InteropProbingApplication.java
> +@EnableWebMvc
Maybe you don't need this for a REST app

2023-02-15 07:42 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Table(name="eservices")
You are right. Continue to use application.properties for jpa properties such as schema, also if I think that Entity should be auto consistent also without Spring.

2023-02-15 12:03 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +        eserviceRepository.updateEserviceStateByEserviceIdAndVersionId(
The newState parameter is already coming from the input DTO and it's scope is to be used into an update query. Is it necessary to create a new Eservice class instance with all null values just to set only the state one?

2023-02-15 12:03 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/rest/EserviceController.java
> +        eserviceService.updateEserviceState(eserviceId, versionId, changeEServiceStateDTO.geteServiceState());
The ChangeEServiceStateDTO is already a DTO, the  eserviceId and versionId are request parameters present in the request URL

2023-02-15 12:03 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/rest/EserviceController.java
> +    public ResponseEntity<Void> updateEserviceFrequency(UUID eserviceId, UUID versionId, ChangeProbingFrequencyDTO changeProbingFrequencyDTO) throws Exception {
What should be the resulting name? ChangeProbingFrequencyRequestDTO? is it necessary to add it the DTO is already defined as request body in the openapi specification's file?

2023-02-15 12:03 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Entity
Every entity's field will be changed via validated input data from API requests. Adding the validations would just result in a duplication of code since if the field will be updated it's because the input provided has overcome its validation at web layer level

2023-02-15 12:04 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Entity
The logging topic hasn't been discussed yet

2023-02-15 12:04 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String state;
yes, the state is an Enum but defined as a warchar in the database table.

2023-02-15 12:04 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String eserviceType;
yes the eserviceType is an Enum but defined as a warchar in the database table.

2023-02-15 12:04 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @GeneratedValue
Which strategy should be put?

2023-02-15 12:04 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Setter
I don't understand why we should add auto-generated code that won't be used for now. This non-used code will lower the code coverage of the JUnit tests and we'll be even probably forced to write additional tests to test functions that have nothing to do with the logics, requiring us to invest more time than the needed one for the tests. In addition, i've tried to add the requested annotations and got this compile error: "Lombok @Builder needs a proper constructor for this class" plus this important warning from Intellij about the usage of @Data for JPA entities: "Using @Data for JPA entities is not recommended. It can cause severe performance and memory consumption issues" suggesting to replace @Data with safe annotations and autogenerated equals() and hashCode().

2023-02-15 13:58 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/InteropProbingApplication.java
> +@EnableWebMvc
Removed from the project

2023-02-15 14:12 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +        eserviceRepository.updateEserviceStateByEserviceIdAndVersionId(
We need a meeting to synchronize us, because we have different ideas in how to implement this app

2023-02-15 14:15 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/rest/EserviceController.java
> +        eserviceService.updateEserviceState(eserviceId, versionId, changeEServiceStateDTO.geteServiceState());
You need to decouple each layer Request -> DTO > Entity

2023-02-15 14:17 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/rest/EserviceController.java
> +    public ResponseEntity<Void> updateEserviceFrequency(UUID eserviceId, UUID versionId, ChangeProbingFrequencyDTO changeProbingFrequencyDTO) throws Exception {
In the Rest Controller the input request body have the suffix Request and the output Response, In the Service layer DTO, in Repository only the Entity Model

2023-02-16 11:40 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Setter
The important is the equals hascode and toString has to be present in every model, if you don't want to use lombok for this for me is good.

2023-02-16 13:49 UTC, nttdata-rtorsoli requested changes

2023-02-16 13:49 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @GeneratedValue
Strategy Sequence and Sequence Generator stuff

2023-02-16 13:49 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String eserviceType;
JPA support enum with @Enumerated(EnumType.STRING)

2023-02-16 13:49 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/repository/EserviceRepository.java
> +    @Modifying(clearAutomatically = true, flushAutomatically = true)
maybe you can use JPA method save, it's simpler

2023-02-16 13:49 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String state;
JPA supports enum with `@`Enumerated annotation

2023-02-16 13:49 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private Timestamp pollingStartTime;
Add `@`Temporal(TemporalType.TIMESTAMP)

2023-02-16 15:36 UTC, nttdata-rtorsoli submitted a review, later dismissed

2023-02-20 17:48 UTC, galales reviewed
As agreed, I'll merge these changes to avoid blocking this first development setup, but let's remember to address points raised during the review

2023-02-20 17:48 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +@Setter
let's remember to add these functions

2023-02-20 17:48 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String eserviceType;
unless major drawbacks, if this configuration allows consistency between code and business logic, I would suggest to add it

2023-02-20 17:48 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private String state;
unless major drawbacks, if this configuration allows consistency between code and business logic, I would suggest to add it

2023-02-20 17:48 UTC, galales commented on src/main/java/it/pagopa/interop/probing/rest/EserviceController.java
> +        eserviceService.updateEserviceState(eserviceId, versionId, changeEServiceStateDTO.geteServiceState());
I agree about decoupling entities by layer

2023-02-20 17:48 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @GeneratedValue
are there any drawbacks using the default strategy here?

2023-02-22 16:20 UTC, galales approved these changes

2023-02-22 16:20 UTC, galales commented on src/test/resources/data.sql
> +version_id uuid NULL
To be sure that tests reflect actual configurations
```suggestion
base_path VARCHAR(255) ARRAY NOT NULL,
eservice_name varchar(255) NOT NULL,
eservice_type varchar(255) NOT NULL,
eservice_id uuid NOT NULL,
last_request timestamp NULL,
polling_end_time time NOT NULL,
polling_frequency int NOT NULL,
polling_start_time time NOT NULL,
probing_enabled boolean NOT NULL,
producer_name varchar(255) NOT NULL,
response_received timestamp NULL,
state varchar(10) NOT NULL,
version_id uuid NOT NULL
```

2023-02-22 16:20 UTC, merged