fixed testdb table definition
pagopa-archive/interop-be-probing-api pull request #3
Opened 2023-02-22 17:09 UTC by acolella92

2023-02-22 17:27 UTC, galales commented on src/test/java/it/pagopa/interop/probing/integration/model/EserviceTest.java
> +        System.out.println("ciao " + eservice.getEserviceName());
```suggestion
```

2023-02-22 17:27 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(columnDefinition = "varchar default 'ACTIVE'")
any reason why this has a default value? 
this field is mandatory in the imported eservices file

2023-02-22 17:27 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/CustomStringArrayType.java
> +        return o;
shouldn't this method create a copy of the object instead of returning the same reference?

on a side note: methods `equals` and `hashCode` have not been actually implemented, it could lead to issues difficult to debug

2023-02-22 17:54 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/CustomStringArrayType.java
> +        return o;
Added implementations

2023-02-22 17:54 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(columnDefinition = "varchar default 'ACTIVE'")
Removed default value

2023-02-23 09:08 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @Column(columnDefinition = "varchar")
It is not important the column definition in our case

2023-02-23 09:19 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="polling_frequency", columnDefinition = "integer default 5")
ORM default is different then DB default, right the DB default but you need also to specify the default value in the field
Integer pollingFrequency = 5

2023-02-23 09:21 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="polling_end_time")
@Temporal(TemporalType.TIME)

2023-02-23 09:22 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private Timestamp responseReceived;
Do nnot use java.sql but java.util

2023-02-23 09:22 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private Time pollingEndTime;
Do nnot use java.sql but java.util

2023-02-23 09:23 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private Time pollingStartTime;
Do nnot use java.sql.Time but java.util.Date with @Temporal(TemporalType.TIME)

2023-02-23 09:24 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private boolean probingEnabled;
if you boolean default is false, then remember also to add default false also on DB DDL.
If you need a nullable field you need to use Boolean but it is not the case.

2023-02-23 09:25 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @NotNull
For String better @NotBlank and use @Size to avoid to insert an huge String exceed DB field definition.
Example Varchar2(255) ->  @size(255)

2023-02-23 09:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @NotNull
Use @Size and @Basic with optional value to false

2023-02-23 09:38 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private long id;
@Column(updatable=false)

2023-02-23 09:39 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private String eserviceName;
Idem as before

2023-02-23 09:40 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="response_received")
use @Temporal

2023-02-23 09:41 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @NotNull
Continue to think that is better to add a field with an @Version annotation for optimistic lock

2023-02-23 09:47 UTC, nttdata-rtorsoli commented on src/test/resources/data.sql
>  CREATE TABLE eservices (
Missing defaults

2023-02-23 09:49 UTC, nttdata-rtorsoli commented on src/test/resources/data.sql
>  id bigint PRIMARY KEY,
Add also DDL for Sequence

2023-02-23 11:31 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @Column(columnDefinition = "varchar")
Removed the column definition

2023-02-23 11:31 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="polling_frequency", columnDefinition = "integer default 5")
Added default value to the field as well

2023-02-23 11:31 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="polling_end_time")
The field type is from java.sql package, which doesn't support the @Temporal annotation. About the usage of java.sql package see comments below.

2023-02-23 11:31 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private Timestamp responseReceived;
It's important to maintain not only the time but even the date informations, this impacts the polling business logics. The Timestamp type has been chosen to reflect the postgres' timestamp column type.

2023-02-23 11:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private Time pollingEndTime;
What is the technical reason to change from java.sql to java.util? The following Oracle official documentation https://docs.oracle.com/javaee/6/tutorial/doc/bnbqa.html states that for Time and Timestamp fields the java.sql package classes should be used. In addition, java.sql is meant to be used when dealing with databases to better fit the SQL types.

2023-02-23 11:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private Time pollingStartTime;
Same of the previous comment

2023-02-23 11:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private boolean probingEnabled;
Ok

2023-02-23 11:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @NotNull
Change done on String fields

2023-02-23 11:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @NotNull
Change done

2023-02-23 11:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private long id;
Change done

2023-02-23 11:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private String eserviceName;
Change done

2023-02-23 11:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="response_received")
Change done

2023-02-23 11:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @NotNull
@Version doesn't support UUID types

2023-02-23 11:57 UTC, acolella92 commented on src/test/resources/data.sql
>  CREATE TABLE eservices (
Added default

2023-02-23 11:58 UTC, acolella92 commented on src/test/resources/data.sql
>  id bigint PRIMARY KEY,
Not necessary, the sequence is autogenerated and as seen in an additional tests done where an insertion of 2 different eservices has been performed, the ids have been correctly set and generated.

2023-02-23 12:31 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="polling_end_time")
java.sql is used only in JDBC env, in JPA you it is better to use java.util.Date (java.sql.Date is a subclass of java.util.Date), but in reality you need to rid of java.util or java.sql and use java.time.
In the case of old fashion style you can use:

import java.util.Date;

`@`Column(name="last_request")
    `@`Temporal(TemporalType.TIMESTAMP)
    private Date lastRequest;

    `@`Column(name="response_received")
    `@`Temporal(TemporalType.TIMESTAMP)
    private Date responseReceived;

    `@`NotNull
    `@`Column(name="polling_end_time")
    `@`Temporal(TemporalType.TIME)
    private Date pollingEndTime;

    `@`NotNull
    `@`Column(name="polling_frequency", columnDefinition = "integer default 5")
    private Integer pollingFrequency = 5;

    `@`NotNull
    `@`Column(name="polling_start_time")
    `@`Temporal(TemporalType.TIME)
    private Date pollingStartTime;

Better use java.time, since Java8 and further

Date and Time field on PostgresSQL need to be created TIMESTAMP WITH TIME ZONE

in spring.properties write:
    spring.jpa.properties.hibernate.jdbc.time_zone=UTC

import java.time.*;

`@`Column(name="last_request", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime lastRequest;

    `@`Column(name="response_received", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime responseReceived;

    `@`NotNull
    `@`Column(name="polling_end_time", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetTime pollingEndTime;

    `@`NotNull
    `@`Column(name="polling_frequency", columnDefinition = "integer default 5")
    private Integer pollingFrequency;

    `@`NotNull
    `@`Column(name="polling_start_time", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetTime pollingStartTime;

2023-02-23 12:31 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private Timestamp responseReceived;
Idem as before

2023-02-23 12:31 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private Time pollingEndTime;
Idem as before

2023-02-23 12:31 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private Time pollingStartTime;
Idem as before

2023-02-23 12:35 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @NotNull
The field for `@`Version need to be a fresh new field on DB and on Entity:

`@`Version
    private OffsetDateTime version;

On DB you create an attribute version not null TIMESTAMP WITH TIME ZONE

2023-02-23 12:40 UTC, nttdata-rtorsoli commented on src/test/resources/data.sql
>  id bigint PRIMARY KEY,
Yes because PostGreSQL make this for you, but for experience, it is always better to manage directly DB resource.
https://www.postgresql.org/docs/8.1/datatype.html#DATATYPE-SERIAL

2023-02-24 08:20 UTC, acolella92 commented on src/test/resources/data.sql
>  id bigint PRIMARY KEY,
We're not using PostgreSQL for unit and integration tests. In compliance with what agreed with @galales, being this a test file, it is not necessary to apply this change

2023-02-24 08:23 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="polling_end_time")
According to what we agreed with @galales, database time fields will be defined with timezone, hence this change will be done

2023-02-24 08:26 UTC, nttdata-rtorsoli commented on src/test/resources/data.sql
>  id bigint PRIMARY KEY,
Alessandro, JPA create an abstraction layer for you , you can use H2 for integration tests and PostgreSQL for production.
JPA convert Entity to the right DDL SQL for you.
But this is a crucial point that need to discuss deeply because you need also to manage DDL version.

2023-02-24 08:29 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="polling_end_time")
Java Date is a great mistake for java language, in JDBC app you need to use java.sql package but in JPA before you need to use only java.util.
You use JPA 2.3 at least so you can use the new package java.time.

2023-02-24 12:57 UTC, nttdata-rtorsoli requested changes

2023-02-24 12:57 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> -    @Column(columnDefinition = "varchar")
Missing name for `@`Column
la columnDefinition make sense only if you create SQL DDL from JPA
However use Varchar2

2023-02-24 12:57 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      private boolean probingEnabled;
la columnDefinition make sense only if you create SQL DDL from JPA, in this case is a reminder for developer

2023-02-24 12:57 UTC, nttdata-rtorsoli commented on src/test/resources/data.sql
>  probing_enabled boolean NOT NULL,
default false also for boolean

2023-02-24 12:57 UTC, nttdata-rtorsoli commented on src/test/resources/data.sql
>  producer_name varchar(255) NOT NULL,
Use Varchar2

2023-02-24 13:00 UTC, nttdata-rtorsoli commented on src/test/resources/data.sql
>  producer_name varchar(255) NOT NULL,
Use WITH TIME ZONE for TIME e TIMESTAMP and set the default to SYSDATE

2023-02-24 13:11 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> -    @Column(columnDefinition = "varchar")
this is not present anymore in the last commit. @Column has been removed from the state field

2023-02-24 13:16 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> -    @Column(columnDefinition = "varchar")
Why? If you remove the '@'Column(name=xxxx) the column take the name of the field, better to write the column name isn't it?

2023-02-24 13:23 UTC, nttdata-rtorsoli commented on src/test/resources/data.sql
>  probing_enabled boolean NOT NULL,
Why do you need SQL files for test environment?
JPA  creates tables automatically for you in integration test

2023-02-24 13:59 UTC, acolella92 commented on src/test/resources/data.sql
>  probing_enabled boolean NOT NULL,
We've set an in-memory database to be used for testing the entity and repository layer in isolation. The in-memory database is not a Postgres one.

2023-02-24 14:04 UTC, nttdata-rtorsoli commented on src/test/resources/data.sql
>  probing_enabled boolean NOT NULL,
But You don not need SQL DDL to create table on H2 (for instance) but JPA create it for you in a automatic way, this may happen also for PostGreSQL (but it is not always used) so if you configure correctly Entities you do not worry to create also SQL DDL for Integration Test but use JPA to create automatically. Otherwise you need to manage also DDL for testing purpose.

2023-02-24 14:05 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> -    @Column(columnDefinition = "varchar")
It depends. In this case, the column name would be exactly the field name and i see no need to duplicate the specification. Usually the name is specified to reflect the database's naming conventions but in this case the column would anyway result in a "state" name. Do we need anyway to add this duplication?

2023-02-24 14:07 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> -    @Column(columnDefinition = "varchar")
I prefer that you duplicate the name also in `@`Column annotation so you are free to change field name without worring about DB.

2023-02-24 14:14 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> -    @Column(columnDefinition = "varchar")
ok change done

2023-02-24 15:00 UTC, acolella92 commented on src/test/resources/data.sql
>  probing_enabled boolean NOT NULL,
We need the scripts for compatibility reasons. There is no in-memory PostgreSQL supported database with no security vulnerabilities but the database we're using and we need these scripts to let the test run.

2023-02-27 09:39 UTC, nttdata-rtorsoli approved these changes

2023-02-27 10:10 UTC, merged