feature/IESP-27
pagopa-archive/interop-be-probing-api pull request #4
Opened 2023-03-03 17:09 UTC by acolella92

2023-03-06 09:19 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/mapstruct/mapper/MapStructMapper.java
>      @Mapping(source = "changeEServiceStateRequest.eServiceState", target = "newEServiceState")
RId of @Mapper(
        componentModel = "spring"
)
if Spring is not used anymore , use default instead

2023-03-06 09:20 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @Column(name="eservice_technology")
Miss `@`size

2023-03-06 09:24 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
>      @Column(name="polling_end_time", columnDefinition = "TIMESTAMP with time zone")
add "as UTC offset" to "TIMESTAMP with time zone" so code is aligned with DB Table

2023-03-06 09:24 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private EserviceState state;
Miss default value to Table definition and model definition

2023-03-06 09:26 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private EserviceTechnology technology;
Miss default value to Table definition and model definition, if any

2023-03-06 09:33 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +            throw new EserviceNotFoundException(ErrorMessages.ELEMENT_NOT_FOUND);
Better interpolate messages to improve meaning of errors with elements of inputData

2023-03-06 09:56 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +    public void updateEserviceProbingState(UpdateEserviceProbingStateDto inputData) throws EserviceNotFoundException {
All good. But I Would like to propose these code, with better functional style:
1) 
Eservice eServiceToUpdate = queryResult.orElseThrow(() -> new EserviceNotFoundException(ErrorMessages.ELEMENT_NOT_FOUND));     
        
        eServiceToUpdate.setProbingEnabled(inputData.isProbingEnabled());
        eserviceRepository.save(eServiceToUpdate);

2 (Better))
`queryResult.map((Eservice eService) -> {
            eService.setProbingEnabled(inputData.isProbingEnabled());
            return eserviceRepository.save(eService);
        }).orElseThrow(() -> new EserviceNotFoundException(ErrorMessages.ELEMENT_NOT_FOUND)); `

2023-03-06 10:32 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private EserviceTechnology technology;
This should always be defined as input data and has big impact on the business logics, since depending if the technology is either REST or SOAP the polling HTTP request will be crafted differently. Instead of setting up a default value which could lead to dirty data or exceptions during the polling flow, i'd rather check the input and block the insertion flow throwing an exception and not risking to add wrong data into the database, @galales what do you think would be better?

2023-03-06 10:32 UTC, nttdata-rtorsoli requested changes
If you need assistance please call me

2023-03-06 10:35 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +            throw new EserviceNotFoundException(ErrorMessages.ELEMENT_NOT_FOUND);
This would break the OWASP error handling cheat sheet (https://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html#java-springmvcspringboot-web-application) which states to always send generic information back to the clients. The flow is meant to be:
1. user send request
2. an exception is thrown and a generic response is sent back to the user
3. the maintenance team checks the logs to find the error reason
@galales what do you think would be better?

2023-03-06 10:46 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +            throw new EserviceNotFoundException(ErrorMessages.ELEMENT_NOT_FOUND);
Good for OWASP but at least remember to log this exception with info enrichment

2023-03-06 11:11 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +            throw new EserviceNotFoundException(ErrorMessages.ELEMENT_NOT_FOUND);
Yes sure, the whole stacktrace will be logged if the exception will occur

2023-03-06 11:46 UTC, galales reviewed
[Blocking] Code formatting needed
[NonBlocking] May I ask to add automatic formatting on, for example, compile?
As per the previous PRs, it would be very useful to commit the formatting configuration file

2023-03-06 11:46 UTC, galales commented on docs/openapi/api-external-interop-v1.yaml
> +          default: false
[Blocking] any reason why this defaults to `false`?

2023-03-06 11:46 UTC, galales commented on src/main/java/it/pagopa/interop/probing/exception/RestExceptionHandler.java
> +import it.pagopa.interop.probing.interop_be_probing_api.model.Problem;
[NonBlocking] out of curiosity, isn't the packages naming convention something like `interopbeprobingapi`?
Or given that we already have the prefix `it.pagopa.interop.probing`, it could be just `it.pagopa.interop.probing.api` (or `it.pagopa.interop.probing.probingapi` to be distinguished by statistics api)

2023-03-06 11:46 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @Column(name="base_path", columnDefinition = "varchar(255) array")
[Blocking] The RFC does not impose a limit, but in my opinion it would be better to increase this limit to 2048

2023-03-06 11:46 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +            OffsetDateTime.now().getDayOfMonth(),
[Blocking] I don't remember if the parameter is exactly this one, but it is required to avoid edge cases
```suggestion
            OffsetDateTime.now(ZoneOffset.UTC).getYear(),
            OffsetDateTime.now(ZoneOffset.UTC).getMonthValue(),
            OffsetDateTime.now(ZoneOffset.UTC).getDayOfMonth(),
```

2023-03-06 11:46 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +            OffsetDateTime.now().getDayOfMonth(),
[Blocking] Same
```suggestion
            OffsetDateTime.now(ZoneOffset.UTC).getYear(),
            OffsetDateTime.now(ZoneOffset.UTC).getMonthValue(),
            OffsetDateTime.now(ZoneOffset.UTC).getDayOfMonth(),
```

2023-03-06 11:46 UTC, galales commented on src/main/java/it/pagopa/interop/probing/util/constant/ErrorMessages.java
> +    public static final String BAD_REQUEST = "The provided data are not valid";
```suggestion
    public static final String BAD_REQUEST = "The provided data is not valid";
```

2023-03-06 11:46 UTC, galales commented on src/test/java/it/pagopa/interop/probing/integration/model/EserviceTest.java
> +                        OffsetDateTime.now().getDayOfMonth(), 0, 0, 0, 0, ZoneOffset.UTC),
I don't think it will impact the test, but for consistency let's add the timezone parameter to all `now()` invocations

2023-03-06 11:52 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private EserviceTechnology technology;
I agree, this value must be `not null` in the db and be present at INSERTion time, this service cannot decide a default value.
The `interop-be-probing-eservice-registry-reader` (which is the first to retrieve this information) must fail if any required field is missing.

2023-03-06 11:52 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private EserviceState state;
same considerations [here](https://github.com/pagopa/interop-be-probing-api/pull/4#discussion_r1126311090)

2023-03-06 11:53 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private EserviceState state;
From a discussion with @galales we agreed that default isn't necessary here because it must be nullable and the data will come from the S3 bucket file

2023-03-06 11:55 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @Column(name="eservice_technology")
This attribute is actually of type EserviceTechnology which is an Enum, is it still required?

2023-03-06 11:59 UTC, galales commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private EserviceState state;
I think there is a typo: it must be `non`-nullable

2023-03-06 13:17 UTC, acolella92 commented on src/test/java/it/pagopa/interop/probing/integration/model/EserviceTest.java
> +                        OffsetDateTime.now().getDayOfMonth(), 0, 0, 0, 0, ZoneOffset.UTC),
Change done, will be present in next commit

2023-03-06 13:20 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    @Column(name="base_path", columnDefinition = "varchar(255) array")
Change done, will be present in next commit

2023-03-06 13:24 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/exception/RestExceptionHandler.java
> +import it.pagopa.interop.probing.interop_be_probing_api.model.Problem;
This is a typo introduced with the micrservice name change, maybe the better solution is to change the package names to it.pagopa.interop.probing.probingapi. If you agree i'll change and commit them with the next push.

2023-03-06 13:34 UTC, galales commented on src/main/java/it/pagopa/interop/probing/exception/RestExceptionHandler.java
> +import it.pagopa.interop.probing.interop_be_probing_api.model.Problem;
sure 👍

2023-03-06 14:30 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/exception/RestExceptionHandler.java
> +import it.pagopa.interop.probing.interop_be_probing_api.model.Problem;
Change done, will be present in the next commit

2023-03-06 15:19 UTC, acolella92 commented on docs/openapi/api-external-interop-v1.yaml
> +          default: false
As agreed, the default has been removed from the openapi specification

2023-03-06 16:28 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/model/Eservice.java
> +    private EserviceState state;
@galales  yes i meant non-nullable, just an error while writing the comment

2023-03-06 18:16 UTC, acolella92 commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +    public void updateEserviceProbingState(UpdateEserviceProbingStateDto inputData) throws EserviceNotFoundException {
Change done locally, i'm getting a Sonarlint major bug issue, maybe we can check it together and decide how to solve it

2023-03-07 08:21 UTC, nttdata-rtorsoli commented on src/main/java/it/pagopa/interop/probing/service/EserviceServiceImpl.java
> +    public void updateEserviceProbingState(UpdateEserviceProbingStateDto inputData) throws EserviceNotFoundException {
It is not mandatory it was suggested only to improve readability and lower verbosity

2023-03-07 08:22 UTC, nttdata-rtorsoli approved these changes, later dismissed

2023-03-07 09:27 UTC, acolella92 commented on src/test/java/it/pagopa/interop/probing/integration/model/EserviceTest.java
> +                        OffsetDateTime.now().getDayOfMonth(), 0, 0, 0, 0, ZoneOffset.UTC),
Removed the change since data type is now OffsetTime and not OffsetDateTime anymore

2023-03-07 09:31 UTC, nttdata-rtorsoli submitted a review, later dismissed

2023-03-07 15:32 UTC, galales approved these changes

2023-03-07 15:35 UTC, nttdata-rtorsoli approved these changes

2023-03-07 15:38 UTC, merged