Feature/IESP-70
pagopa-archive/interop-be-probing-api pull request #9
Opened 2023-03-16 12:03 UTC by melissa-dellorco

2023-03-16 14:45 UTC, nttdata-rtorsoli submitted a review, later dismissed

2023-03-17 08:44 UTC, galales requested changes

2023-03-17 08:44 UTC, galales commented on src/main/java/it/pagopa/interop/probing/probingapi/filter/MDCWebFilter.java
> +			MDC.put(LoggingPlaceholders.TRACE_ID_PLACEHOLDER, "OID= " + UUID.randomUUID().toString().toLowerCase());
I suppose this is the correlation id, the correct label is `CID`.
These values are surrounded by square brackets in order to improve log analysis. Example:
`[CID=xyz] plus the log message`

2023-03-17 11:23 UTC, melissa-dellorco commented on src/main/java/it/pagopa/interop/probing/probingapi/filter/MDCWebFilter.java
> +			MDC.put(LoggingPlaceholders.TRACE_ID_PLACEHOLDER, "OID= " + UUID.randomUUID().toString().toLowerCase());
done

2023-03-17 16:28 UTC, nttdata-rtorsoli approved these changes

2023-03-17 16:29 UTC, galales approved these changes

2023-03-17 16:29 UTC, merged